#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_login:
  path: /
  controller: App\Controller\SecurityController::login
app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout
app_register:
  path: /register
  controller: App\Controller\RegistrationController::register
search_users:
  path: /user/back/searchUsers
  controller: App\Controller\UserController::searchUsers
  methods: [GET]
